name: Daily Scrape (Safe Mode)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "22 2 * * *"   # ~05:22 Africa/Cairo

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          SITES_CSV_PATH: Sites_Catalog.csv
          OUT_DIR: out
        run: |
          python scrape.py

      - name: Show outputs
        run: |
          echo "----- out dir -----"
          ls -la out || true
          echo "----- git status -----"
          git status --porcelain || true

      - name: Commit & push results (only if changed)
        run: |
          git add out/*.csv 2>/dev/null || true
          if ! git diff --cached --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "Update scraped data [skip ci]"
            git push
            echo "Changes pushed."
          else
            echo "No changes to commit."
          fi

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scrape-outputs
          path: out/*
          if-no-files-found: ignore
