name: Daily Scrape (Safe Mode)

on:
  workflow_dispatch: {}          # lets you run it manually
  schedule:
    - cron: "22 2 * * *"        # runs every day at 02:22 UTC

permissions:
  contents: write                # allow the job to push CSVs back to repo

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          SITES_CSV_PATH: Sites_Catalog.csv
          OUT_DIR: out
        run: |
          python scrape.py

      - name: Commit & push results (only if changed)
        run: |
          git add out/*.csv 2>/dev/null || true
          if ! git diff --cached --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "Update scraped data [skip ci]"
            git push
            echo "Changes pushed."
          else
            echo "No changes to commit."
          fi

      - name: Upload artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scrape-outputs
          path: out/*
          if-no-files-found: ignore
                - name: Trigger Make Webhook
        run: |
          curl -X POST https://hook.us2.make.com/v8xg1sfegycppt03qbkodgx9eesaabl6
